### ISSUE TITLE
AttributeError: 'YTMusic' object has no attribute 'headers'

### ISSUE THREAD

**Issue by almostserious** [OzymandiasTheGreat/mopidy-ytmusic#1]
Im currently trying to get your ytmusic extension to run.
However, im unable to setup ytmusic correctly.

I was able to create the required auth.json but maybe its not correct?

When running mopidy i get the following errors:

```
  Got un-handled exception from YTMusicBackend
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 241, in _actor_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 406, in start_backends
    config=config, audio=audio
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/backend.py", line 384, in __init__
    API = YTMusic(config["ytmusic"]["auth_json"])
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 93, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
AttributeError: 'YTMusic' object has no attribute 'headers'
```

**Comment by OzymandiasTheGreat** [comment]
Hey, thanks for checking this out.

The error comes from the library I use to connect to YouTube Music, [ytmusicapi](https://github.com/sigma67/ytmusicapi).
I just check their sources and it looks like headers are set in a try block.
If there's a problem setting headers it must print additional message before this one stating what's the error.
Could you check again and post that? It reads like this : "Failed loading provided credentials. Make sure to provide a string or a file path. Reason: ...". The important part comes after "Reason".

**Comment by almostserious** [comment]
Unfortunately I do not get any additional error messages. However, i will try again with a fresh auth.json. Could you maybe post the content of the auth.json how it is supposed to look?

mine looks like this:

```
{
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.5",
    "Content-Type": "application/json",
    "Cookie": "VISITOR_INFO1_LIVE=REDACTED; GPS=1; YSC=REDACTED; PREF=volume=100; SID=REDACTED_REDACTED.; __Secure-3PSID=REDACTED.; HSID=REDACTED; SSID=REDACTED; APISID=REDACTED/REDACTED; SAPISID=REDACTED/REDACTED; __Secure-HSID=REDACTED; __Secure-SSID=REDACTED; __Secure-APISID=REDACTED/REDACTED; __Secure-3PAPISID=REDACTED/REDACTED; CONSENT=YES+DE.de+20160424-15-0; LOGIN_INFO=REDACTED-REDACTED:REDACTED; SIDCC=REDACTED_PB_REDACTED; ST-1rmuya0=csn=REDACTED.&itct=REDACTEDl",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0",
    "X-Goog-AuthUser": "0",
    "X-Goog-Visitor-Id": "REDACTED%3D%3D",
    "x-origin": "https://music.youtube.com"
}

```
I just redacted all the codes as i have no idea what of this is important

**Comment by almostserious** [comment]
Indeed it was just a misconfiguration. I managed to make it work by doing the auth.json again.
