### ISSUE TITLE
Playing Premium Tracks

### ISSUE THREAD

**Issue by Ham5andw1ch** [OzymandiasTheGreat/mopidy-ytmusic#12]
I am a Youtube Premium subscriber and have some albums that are available only to premium members.

Here is one such album: https://music.youtube.com/browse/MPREb_9dr3eORVCHz

When trying to play the album, despite me copying my request headers in and being logged in through the browser, the premium tracks on this album are not available to me. When playing them, I get the following error.

"ERROR: This video is only available to Music Premium members"

Is there any way this functionality can be added? I have modifying the youtubedl constructor to include my cookies.txt to no avail.

**Comment by OzymandiasTheGreat** [comment]
Basically, can you download the album with youtube-dl? If no, you should open an issue there.

**Comment by Ham5andw1ch** [comment]
Yes. If I pass my cookies.txt into youtube-dl, it works fine. I think my changes actually didn't go through when I tried to fix it. I am trying again, but I believe the fix would be to have a user copy their cookies similarly to how they copy their request headers. Just make it a config option.

**Comment by OzymandiasTheGreat** [comment]
Shouldn't be necessary, as headers also include all the cookies, just parse them out and figure out where to pass them.
Thanks, you pretty much provided everything I need to get this working. I'm currently sick with some flu like virus, but I'll look into it next week probably.

**Comment by Ham5andw1ch** [comment]
Can confirm after passing my cookiefile in the constructor that it works. Get well soon and happy new year!
