### ISSUE TITLE
Ready for release.

### ISSUE THREAD

**Issue by impliedchaos** [OzymandiasTheGreat/mopidy-ytmusic#15]
But only when you're feeling up to it!  Seriously.

OK, I resolved the conflict, and merged (I meant to merge into a new branch and let you do the final merge to master, but somehow I screwed that up and it's all in master).  

I've been testing and everything appears to be OK (after a quick fix).  So we should be ready.  After release, I'll put in a pull request to mopidy/website to add https://mopidy.com/ext/ytmusic/ and resolve issue #2

**Comment by OzymandiasTheGreat** [comment]
I'm pretty good today, thank you.

I pulled latest changes and ran a quick test. It's downright awesome what you've done with this extension, thank you.
Published to PyPI, should be live now.
As for the mopidy/website, thank you, I've been meaning to do that for a while now, it sort of slipped my mind.

**Comment by OzymandiasTheGreat** [comment]
Just a side note, with your changes we made Mopidy with Youtube Music more impressive and usable than Mopidy with Spotify.
Again, thank you.

**Comment by impliedchaos** [comment]
No, thank you!  I just wanted mopidy to work like it used to with Google Play Music, and thanks to your code now it does.
Oh, I need to update the changelog and push that out as well.

**Comment by Ham5andw1ch** [comment]
Hats off to you. This update has fixed almost every issue I had with mopidy-ytmusic. Thanks for your hard work!
