### ISSUE TITLE
is there a "my playlists" entry?

### ISSUE THREAD

**Issue by thanxx** [OzymandiasTheGreat/mopidy-ytmusic#18]
Hi, 
Just installed the extension and after the auth procedure, all I see is these 3 folders
Shouldn't there be "My playlists" from my account?
![image](https://user-images.githubusercontent.com/21316174/106455166-81c46000-6494-11eb-947e-7b6324c0fb5e.png)

**Comment by impliedchaos** [comment]
No, your playlists will show up under the "playlists" section of mopidy.  However it looks like the authentication didn't succeed, as your history isn't showing up (as "Recently Played"), this is what I see:
![image](https://user-images.githubusercontent.com/10725029/106455719-8ff58a80-645a-11eb-9638-f90c0fdd39cc.png)

Can you verify that the file that you set your "auth_json" to exists and has data in it?

**Comment by thanxx** [comment]
Yes, that was the wrong config on my side, now I see all my playlists
thank you
