### ISSUE TITLE
loading playlist .m3u8 with mpc does not work

### ISSUE THREAD

**Issue by chicco64** [OzymandiasTheGreat/mopidy-ytmusic#24]
Hi !
I would like to load my playlist through the "mpc load playlist" command.
Mopidy cannot play the "saved" playlist in m3u8 format; it is possible to play the playlist only through the "musicbox" graphic interface by manually selecting the playlist that appears on the network, and not the one saved in m3u8 format.
Is it possible to start the playlist "on the net" through the command line?
Perhaps using the "public" link that distinguishes that specific playlist (eg. https://music.youtube.com/playlist?list=xxx_xxx_xxx)
Thanks for your help

**Comment by impliedchaos** [comment]
Yeah, you can just change the URL from "https://music.youtube.com/playlist?list=XXXXX" to "ytmusic:playlist:XXXXX".  Then you can add that url via a web frontend or from mpc as "mpc add ytmusic:playlist:XXXXX"

**Comment by chicco64** [comment]
Great, the "mpc add ytmusic: playlist: XXXXX" method works perfectly !
Would you be so kind to explain the other method, "via a web frontend", perhaps with a concrete example?
eg. my current address is: 
http://xx.xx.xx.xx:6680/musicbox_webclient/index.html#nowPlaying
Many thanks !

**Comment by impliedchaos** [comment]
It's the same, you're just manually entering it into musicbox.  Navigate to "Queue" and click on the "+" button on the top right.  Then just type the URI you created into the dialog.

![image](https://user-images.githubusercontent.com/10725029/108122382-30aa9380-7072-11eb-890c-b23469e8b1cf.png)

**Comment by chicco64** [comment]
perfect, many thanks!

**Comment by bendschs** [comment]
for some reason this only works for me if tracks/playlists are already cached, or at least were searched for before through the webfrontend. otherwise mpc fails with  "directory or file not found".
