### ISSUE TITLE
Setup fails: Permission Denied

### ISSUE THREAD

**Issue by mfussi** [OzymandiasTheGreat/mopidy-ytmusic#27]
Hi,

I am running into a permission error when trying to create the auth.json using the setup command.

`PermissionError: [Errno 13] Permission denied: '/home/pi/auth.json'`

using following command:

`sudo mopidyctl ytmusic setup`

What could be the issue? my sudo user has access to the directory /home/pi.

Best Regards
Markus

**Comment by impliedchaos** [comment]
Hi Markus,

While sudo (the root user) has access to your `/home/pi` directory, mopidyctl actually instructs the mopidy daemon itself to perform the file creation, and that's running as the mopidy user, which probably doesn't have write access to /home/pi.

For a work around, check out this section of the readme: https://github.com/OzymandiasTheGreat/mopidy-ytmusic#note-for-users-running-mopidy-as-a-service

Thanks!
Dave

**Comment by mfussi** [comment]
Thank you for the fast response. Works like a charm.

Sorry for not reading the instructions to the end.
