### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by chicco64** [OzymandiasTheGreat/mopidy-ytmusic#3]
hi,
I have installed your application as indicated
but i can't complete through "mopidy ytmusic setup"
could you give me more detailed information? thank you

**Comment by OzymandiasTheGreat** [comment]
What exactly doesn't work? That whole command is just a thin wrapper for the library I'm using here,
so if there's a bug there may not be much I can do.

**Comment by chicco64** [comment]
Hi !
this is my installation procedure (under debian10);
1) I install mopidy as per the standard procedure;
2) I install Mopidy-YTMusic;
3) I add in /etc/mopidy/mopidy.conf this lines:

[ytmusic]
enabled = true
auth_json = ./auth.json

4) run "mopidy ytmusic setup"
this is the result:

INFO     2020-09-18 13:07:48,621 [21060:MainThread] mopidy.__main__
  Starting Mopidy 3.0.2
INFO     2020-09-18 13:07:48,628 [21060:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2020-09-18 13:07:48,629 [21060:MainThread] mopidy.config
  Loading config from file:///root/.config/mopidy/mopidy.conf
INFO     2020-09-18 13:07:48,629 [21060:MainThread] mopidy.config
  Loading config from command line options
INFO     2020-09-18 13:07:48,701 [21060:MainThread] mopidy.__main__
  Enabled extensions: stream, http, file, softwaremixer, musicbox_webclient, mpd, m3u
INFO     2020-09-18 13:07:48,701 [21060:MainThread] mopidy.__main__
  Disabled extensions: ytmusic
WARNING  2020-09-18 13:07:48,701 [21060:MainThread] mopidy.__main__
  Found ytmusic configuration errors. The extension has been automatically disabled:
WARNING  2020-09-18 13:07:48,702 [21060:MainThread] mopidy.__main__
    ytmusic/auth_json must be set.
WARNING  2020-09-18 13:07:48,702 [21060:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
ERROR    2020-09-18 13:07:48,702 [21060:MainThread] mopidy.__main__
  Unable to run command provided by disabled extension ytmusic

5) if I also add in /root/.config/mopidy/mopidy.conf this lines:

[ytmusic]
enabled = true
auth_json = ./auth.json

and after run "mopidy ytmusic setup"

this is the result:

INFO     2020-09-18 13:11:38,114 [21079:MainThread] mopidy.__main__
  Starting Mopidy 3.0.2
INFO     2020-09-18 13:11:38,121 [21079:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2020-09-18 13:11:38,122 [21079:MainThread] mopidy.config
  Loading config from file:///root/.config/mopidy/mopidy.conf
INFO     2020-09-18 13:11:38,122 [21079:MainThread] mopidy.config
  Loading config from command line options
INFO     2020-09-18 13:11:38,193 [21079:MainThread] mopidy.__main__
  Enabled extensions: musicbox_webclient, softwaremixer, stream, mpd, m3u, http, file, ytmusic
INFO     2020-09-18 13:11:38,193 [21079:MainThread] mopidy.__main__
  Disabled extensions: none
Enter the path where you want to save auth.json:/tmp
File already exists!

but no file is created in / tmp

If you can please tell us the exact installation procedure (step by step), and the insertion of the credentials (user, password) 
for YT music
Thank you very much !

**Comment by Deep-Six** [comment]
I can also confirm, this is happening on Arch Linux, I am having similar issues. I have the following errors:

Failed loading provided credentials. Make sure to provide a string or a file path. Reason: Expecting value: line 1 column 1 (char 0)
ERROR    2020-09-18 12:47:08,788 [8769:MainThread] mopidy.commands
  Got un-handled exception from YTMusicBackend
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mopidy/commands.py", line 241, in _actor_error_handling
    yield
  File "/usr/lib/python3.8/site-packages/mopidy/commands.py", line 405, in start_backends
    backend = backend_class.start(
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/home/jhenkel/.local/lib/python3.8/site-packages/mopidy_ytmusic/backend.py", line 384, in __init__
    API = YTMusic(config["ytmusic"]["auth_json"])
  File "/home/jhenkel/.local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
AttributeError: 'YTMusic' object has no attribute 'headers'


I wrapped the auth_json = in ""'s and got passed the Failed loading...however I got this..
 Starting Mopidy backends: YTMusicBackend, FileBackend, M3UBackend, StreamBackend
INFO     2020-09-18 12:49:38,298 [9574:Audio-2] mopidy.audio.actor
  Audio output set to "autoaudiosink"
ERROR    2020-09-18 12:49:38,452 [9574:MainThread] mopidy.commands
  Got un-handled exception from YTMusicBackend
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mopidy/commands.py", line 241, in _actor_error_handling
    yield
  File "/usr/lib/python3.8/site-packages/mopidy/commands.py", line 405, in start_backends
    backend = backend_class.start(
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/home/jhenkel/.local/lib/python3.8/site-packages/mopidy_ytmusic/backend.py", line 384, in __init__
    API = YTMusic(config["ytmusic"]["auth_json"])
  File "/home/jhenkel/.local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
TypeError: string indices must be integers

I have validated that there is a Cookie entry in my auth.json...

Happy to help troubleshoot..

**Comment by chicco64** [comment]
Hi!
Forgive me, but I didn't understand ...
were you able to solve the problem or not?
I did a fresh install but everything remained the same (don't work)
Can you help me ? thank you

**Comment by Deep-Six** [comment]
No, I was unable to resolve it, haven't looked at the code too much yet.

**Comment by chicco64** [comment]
hi, could you solve the problems indicated?
thank you

**Comment by Deep-Six** [comment]
I am not the original maintainer, and don't expect I'll be in the position to solve the problem @OzymandiasTheGreat  is likely in the best position to assist, I am happy to offer additional assistance.

**Comment by Deep-Six** [comment]
I believe this is the library @OzymandiasTheGreat  is referencing, https://github.com/sigma67/ytmusicapi issues might be therein.
