### ISSUE TITLE
Track not playable (no streams found)

### ISSUE THREAD

**Issue by rebernet** [OzymandiasTheGreat/mopidy-ytmusic#31]
I run into to following error today when playing a song:

```
May 18 14:55:24 ubuntu mopidy[123169]: ERROR    [YTMusicBackend-3] mopidy_ytmusic No streams found for 8xsL8TKxAao. Falling back to youtube-dl.
May 18 14:55:24 ubuntu mopidy[123169]: WARNING  [Core-15] mopidy.core.tracklist Track is not playable: ytmusic:track:8xsL8TKxAao
```

Yesterday everything worked fine. I am authenticated and able to view artists etc.

Any ideas?

**Comment by impliedchaos** [comment]
If I directly link to it: https://www.youtube.com/watch?v=8xsL8TKxAao, I get "No Video Available" and I can't play the track via https://music.youtube.com/watch?v=8xsL8TKxAao, either.  I think the issue is with this particular track.

**Comment by rebernet** [comment]
Thanks for your fast reply.

Both of your suggested direkt links work for me. But it is a general problem as any track won't play. Might this again be an issue with Iris? Weird thing is yesterday everything was fine and I haven't changed my setup. I also tried to reauth.

**Comment by rebernet** [comment]
I tried a fresh mopidy + YTMusic + Iris installation within a docker container:

It worked to play any track **before** setting up the authentication. After ```mopidyctl ytmusic setup``` creating the auth.json and accessing my own premium account I encountered the same error. Feels like google is blocking something but I have no idea how to further debug this...

**Comment by impliedchaos** [comment]
Sorry, didn't mean to disappear on you like that, got caught up with work/family/life.

It looks like Google has made some more changes and this is likely the issue.  ytmusicapi just released v0.17.1 a few minutes ago (which has some breaking changes and really should have been v0.18,0, but whatever) and that release seems to be related to Google's changes.  I'm going to (sometime soon) upgrade the package to use the new version of ytmusicapi and then spend time fixing what that breaks.  Once I get everything working I'll push the changes and hopefully this will solve your issues.

**Comment by rebernet** [comment]
No worries, I know exactly what you mean :)

I tried do play around with your code but did not manage to run/test in a pip virtualenv. How do you develop/improve this code?

Anyways, thanks for helping. Let me know if I can assist you. Happy to contribute.

**Comment by rebernet** [comment]
Tried your potential fix. It brings me further in the ```playback.py```. The stream is now found, but the decoded URL is forbidden:

```
May 22 05:26:44 ubuntu mopidy[142495]: INFO     [YTMusicBackend-3] mopidy_ytmusic YTMusic Found AUDIO_QUALITY_HIGH stream with 259394 bitrate for zBqW6yKz8WA
May 22 05:26:44 ubuntu mopidy[142495]: ERROR    [YTMusicBackend-3] mopidy_ytmusic YTMusic found forbidden URL. Updating player URL now.
May 22 05:26:44 ubuntu mopidy[142495]: WARNING  [Core-15] mopidy.core.tracklist Track is not playable: ytmusic:track:zBqW6yKz8WA
```

**Comment by impliedchaos** [comment]
Yes, some big changes were made to youtube's backend.  ytmusicapi had to do another release, and I'm updating everthing to use that now.
Should be done soon.

**Comment by impliedchaos** [comment]
OK, just released 0.2.4 which should hopefully solve this.

**Comment by rebernet** [comment]
Thank you @impliedchaos for your fast commit. It is fixed. You can close the issue.

**Comment by sarab97** [comment]
Im still facing same issue
