### ISSUE TITLE
Too many API queries / Not everything is always loaded

### ISSUE THREAD

**Issue by Hoerli1337** [OzymandiasTheGreat/mopidy-ytmusic#33]
Great extension so far!
Setup is a bit stupid with the cookie, but doable.

In Liked Songs only a maximum of 5 songs are loaded, although there should be many many more.
Sometimes no results are shown in the categories either.
I see in the log that apparently too many requests are sent via the API:
```
Jun 12 13:18:38 raspberrypi4B mopidy[856]:     return request('get', url, params=params, **kwargs)
Jun 12 13:18:38 raspberrypi4B mopidy[856]:   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
Jun 12 13:18:38 raspberrypi4B mopidy[856]:     return session.request(method=method, url=url, **kwargs)
Jun 12 13:18:38 raspberrypi4B mopidy[856]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
Jun 12 13:18:38 raspberrypi4B mopidy[856]:     resp = self.send(prep, **send_kwargs)
Jun 12 13:18:38 raspberrypi4B mopidy[856]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
Jun 12 13:18:38 raspberrypi4B mopidy[856]:     r = adapter.send(request, **kwargs)
Jun 12 13:18:38 raspberrypi4B mopidy[856]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
Jun 12 13:18:38 raspberrypi4B mopidy[856]:     raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s.youtube.com', port=443): Max retries exceeded with url: [Cookie]
```

I have the following config:
```
[ytmusic]
enabled = true
auth_json = /home/musikbox/auth.json
auto_playlist_refresh = 60
youtube_player_refresh = 15
playlist_item_limit = 1000
subscribed_artist_limit = 100
enable_history = true
enable_liked_songs = true
enable_mood_genre = true
enable_scrobbling = true
stream_preference =
  141
  251
  140
verify_track_url = true
```

(I have a premium account)

I also tried to recreate the auth.json via setup, once I add the header response I can't press CTRL + D. I can't get the auth.json to work.
Just nothing happens.
Have therefore replaced the cookie in the previously saved auth file by hand.

**Comment by OzymandiasTheGreat** [comment]
Looks like your cookie is rejected. Re: Ctrl+D not working: press enter, then Ctrl+D.
I'm hoping this will fix your issue, if not - do come back.

**Comment by Hoerli1337** [comment]
Sorry for the delayed feedback.
Have now tried it again.
2x CTRL + D in quick succession has also helped here.

After a restart of Mopidy have now loaded the playlists like liked songs also.
