### ISSUE TITLE
Plug-in useless since a couple of weeks.

### ISSUE THREAD

**Issue by herkow** [OzymandiasTheGreat/mopidy-ytmusic#45]
Everything was working flawlessly until almost 12 days ago. At first the tracks started to pause for 4 seconds, then some seconds of silence, and now tracks don't even load. Same thing is happening to YouTube plugin. Debian 11 headless, nothing was changed in the system, no updates, not even a reboot. I guess is something related to Google APIs. Premium user BTW.

**Comment by zonywhoop** [comment]
Was running into some of these same issues then came across [Issue 41](https://github.com/OzymandiasTheGreat/mopidy-ytmusic/issues/41) and did an upgrade of pytube to 11.0.2 and all now works.  For me I did the following to get everything working again:
`pip3 install -U pytube`

**Comment by herkow** [comment]
> Was running into some of these same issues then came across [Issue 41](https://github.com/OzymandiasTheGreat/mopidy-ytmusic/issues/41) and did an upgrade of pytube to 11.0.2 and all now works. For me I did the following to get everything working again: `pip3 install -U pytube`

Thank you very much! It's working now!
