### ISSUE TITLE
Latest version has no setup.py file

### ISSUE THREAD

**Issue by eschava** [OzymandiasTheGreat/mopidy-ytmusic#6]
The latest version has no setup.py file and isn't autoregistered in the mopidy

**Comment by OzymandiasTheGreat** [comment]
Yes, sorry, I messed up migration to poetry.
Need to add entry point configuration to pyproject.toml and setup.py should be autogenerated.
I'm currently dealing with flu, so sorry for delays. I'll get to it once I'm better.
